### ISSUE TITLE
Build issue.

### ISSUE THREAD

**Issue by dsx12** [gen0cide/gscript#109]
I followed every step but for some reason after building there is no ./gscript file compiled?

when I run ./gscript I receive:

"bash: gscript: command not found"

any ideas?

**Comment by capnspacehook** [comment]
Your GOPATH might not be in your PATH. Try adding your GOPATH to the PATH variable in your bashrc, and sourcing your bashrc to load the changes. Then you should be able to call gscript anywhere

**Comment by dsx12** [comment]
admin@arch ~$ echo $GOPATH
/home/admin/dev/go:

?

**Comment by dsx12** [comment]
admin@kali ~$ echo $GOPATH
/home/admin/dev/go:

?

**Comment by ahhh** [comment]
This is not a gscript build issue, it's a basic golang usage issue. I just ran `go get github.com/gen0cide/gscript/cmd/gscript` on a linux/amd64 system w/ go1.10.3 and it properly builds and added the gscript binary to $GOPATH/bin/gscript

As a systems test, can you go get other binaries and do they work properly?
