### ISSUE TITLE
current user without domain

### ISSUE THREAD

**Issue by alecmoran1** [gen0cide/gscript#110]
Thanks for the creation of gscript. There may be an easy way to my problem, but I can't find a way out. How can I get the current users' username without the domain or the workgroup. i.e:
[engine:helloworld.gs]  INFO console.log >>> Our user is: AJ\AJ

This is how I am calling it:

        var user = user2.Current();
        console.log("Our user is: "+user[0].Username);

Thanks!

**Comment by jackson5-sec** [comment]
Why not just parse it out of the user variable with string split?
https://stackoverflow.com/questions/16551354/how-to-split-a-string-and-assign-it-to-variables-in-golang

**Comment by vyrus001** [comment]
this question is not specific to GScript per say, so much as it is the standard lib. And, at that, it is more of a design concern than a functionality issue, I'm going to go ahead and close this but am available for conversation if a refactor is required.
