### ISSUE TITLE
gscript 0.1.0 Feature List

### ISSUE THREAD

**Issue by gen0cide** [gen0cide/gscript#45]
I wanted to document some of my thoughts on what features I'd like to see in gscript for us to take it to v0.1.0, the first "stable" release I'd like to ship.

# New Functions

- [x] `FilePerms(path, 0755, recursive)` - allows a script to change the permissions of files and directories, including recursively.
- [x] `FileStat(path)` - retrieve the modified/access/create times for a given file or directory.
- [x] `SetModTime(path, timestamp)` - Set the modified time of a file.
- [x] `SetAccessTime(path, timestamp)` - Set the access time of a file.
- [x] `SetCreateTime(path, timestamp)` - Set the create time of a file.
- [x] `FindProcess(searchterm)` - Find processes that match a specific regular expression.
- [ ] `DetectSandbox()` - Detect if the value is running in a sandbox.
- [ ] `DetectAV()` - Detect AntiVirus that might be running on the machine.
- [x] `SelfPath()` - Get current path to the running gscript executable.
- [x] `InstallSystemService(svc_config)` - Allows a system service to be installed (cross platform). `svc_config` is a new data structure that will need to be defined.
- [ ] `RenderTemplate(template_bytes, vars)` - Allows the user to embed a golang template and render it at runtime.

# Compiler Enhancements

- [x] Move compiler and runtime into their own sub packages. This will reduce final binary size.
- [x] Minify gscript's before embedding script into final binary.
- [x] Implement better embedded compression to reduce binary size.
- [x] Strip symbols from final binary.
- [x] Create new subcommand `new` that writes a gscript template to a location of your choice.
- [x] Add `--upx` flag to `compile` command to UPX the final binary to the smallest possible size.
- [ ] Implement simple encryption for payloads.
- [ ] Port GOTTI binary obfuscation to the gscript compiler.

# New Macros

- [ ] `//require:/path/to/lib.gs` - This will allow a gscript to reference custom functions from a javascript file. The gscript library should NOT implement the hook functions and the compiler will return an error if it does.
- [x] `//priority:$VAL` - Allows the user to specify lexical ordering of scripts. Scripts without priority will default to priority of 100. All gscripts of a similar priority will be executed concurrently.
- [ ] `//os:windows` - Allows the user to specify what OS this gscript is intended for, preventing bundling of incompatible gscripts into the final binary.
- [ ] `//arch:386` - Same as `//os` but for architecture.
- [x] `//timeout:30` - Allows the user to set a timeout for this gscript to prevent it from hanging during execution. Default will be set to 10 seconds.

# Bug Fixes

- [x] Fix shell incompatibility with windows terminals.
- [x] Change compiler output prefix from GENESIS to GSE.
- [x] Fix Halt() command to stop the entire gscript binary including all goroutines and VMs.
- [x] Implement a file not found timeout on the `//import_url` macro.
- [ ] Migrate process injection to an interface that gets satisfied for all platform types.

# Tech Debt

- [x] TBD, but definitely will be some.
- [x] More documentation needed.
- [x] README.md redesign to improve user learning.

**Comment by vyrus001** [comment]
the one thing I would really like is a way to edit registry commands, that
with the ability to place files on disk will allow me to rappidly setup
persistance.

**Comment by gen0cide** [comment]
We got most of it done! v0.1.0 is out!
