### ISSUE TITLE
Gscript 1.0.0 Feature Spec

### ISSUE THREAD

**Issue by gen0cide** [gen0cide/gscript#53]
I wanted to document some of my thoughts on what features I'd like to see in gscript for us to take it to v0.2.0, the first "stable" release I'd like to ship.

# Engine

- [x] Make `BeforeDeploy()` and `AfterDeploy()` hooks optional, but support older scripts.
- [x] Expose the command line arguments to a GSCRIPT via an `ARGS` object.
- [ ] Make progress on FreeBSD and OpenBSD support.
- [ ] Create a native API for binary self deletion on all platforms.

# Compiler

- [x] Expose a map of defined functions and variables
- [x] Implement a more intelligent AST walker
- [x] Implement a linker that analyzes a gscript's targets and only includes standard library functions that are defined by the included scripts.
- [ ] Be able to point the compiler at different engines revisions or standard libraries.
- [x] Implement packages so `WriteFile()` becomes `Files.WriteFile()`
- [x] Implement simple encryption for payloads.
- [x] Port GOTTI binary obfuscation to the gscript compiler.
- [x] Update post compilation obfuscation to support dynamic analysis of identifiable strings.

## New Macros

- [ ] `//require:/path/to/lib.gs` - This will allow a gscript to reference custom functions from a javascript file. The gscript library should NOT implement the hook functions and the compiler will return an error if it does.
- [ ] `//os:windows` - Allows the user to specify what OS this gscript is intended for, preventing bundling of incompatible gscripts into the final binary.
- [ ] `//arch:386` - Same as `//os` but for architecture.

# Debugger

- [x] Allow the debugger to be compiled into a final binary for debugging a final produced binary.

# CLI

- [x] Have `gscript update` use `go get -u` to update the standard library, as well as the binary.

# Standard Library

- [x] Move YAML function definitions to comment based decorators in the Golang function.
- [x] Decouple the STDLIB from the engine, so that individual stdlib packages can be included.
- [x] Create a Golang based regular expression package with common methods present.

## New Functions

- [x] `DetectSandbox()` - Detect if the value is running in a sandbox.
- [x] `DetectAV()` - Detect AntiVirus that might be running on the machine.
- [ ] `RenderTemplate(template_bytes, vars)` - Allows the user to embed a golang template and render it at runtime.

# Bug Fixes

- [x] Fix issue packing large files - implement heap allocation segments for large files so that the runtime can assemble them at runtime.
- [x] Migrate process injection to an interface that gets satisfied for all platform types.

# Tech Debt

- [ ] TBD, but definitely will be some.

**Comment by ahhh** [comment]
We should plan a dev sprint / hackathon for these items
